name: Daily Site Update

on:
  schedule:
    # Run twice daily at 9 AM and 9 PM UTC (6 AM and 6 PM Brazil time)
    - cron: '0 9 * * *'
    - cron: '0 21 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  trigger-vercel-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Vercel Deploy Hook is configured
        run: |
          if [ -z "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}" ]; then
            echo "⚠️ VERCEL_DEPLOY_HOOK_URL secret not configured"
            echo "📝 To complete setup:"
            echo "   1. Go to Vercel Dashboard → Project → Settings → Git"
            echo "   2. Create a Deploy Hook"
            echo "   3. Copy the hook URL"
            echo "   4. Add it to GitHub Secrets as VERCEL_DEPLOY_HOOK_URL"
            echo "   5. Re-run this workflow"
            exit 1
          else
            echo "✅ VERCEL_DEPLOY_HOOK_URL is configured"
          fi
          
      - name: Trigger Vercel Deploy Hook
        run: |
          echo "🚀 Triggering Vercel deployment..."
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
          
      - name: Log deployment trigger
        run: |
          echo "✅ Triggered daily rebuild at $(date)"
          echo "🇧🇷 This ensures today's games are always current"