name: Test Secret Configuration

on:
  workflow_dispatch: # Manual trigger only

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Test VERCEL_DEPLOY_HOOK_URL secret
        run: |
          if [ -z "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}" ]; then
            echo "❌ VERCEL_DEPLOY_HOOK_URL secret is NOT configured"
            echo "Secret value is empty or missing"
            exit 1
          else
            echo "✅ VERCEL_DEPLOY_HOOK_URL secret IS configured"
            echo "Secret has value (showing first 50 characters):"
            echo "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}" | cut -c1-50
            echo "..."
          fi
          
      - name: Test Deploy Hook (if secret exists)
        if: success()
        run: |
          echo "🚀 Testing deploy hook..."
          response=$(curl -s -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}")
          echo "Response: $response"
          
          # Check if response contains job id (indicates success)
          if echo "$response" | grep -q '"job"'; then
            echo "✅ Deploy hook test successful!"
          else
            echo "❌ Deploy hook test failed"
            echo "Response: $response"
            exit 1
          fi